# This workflow deploys a new release on PyPI once a pull request is closed

name: Deploy to PyPI

on:
  push:
    tags:
      - 'v*'

jobs:
  pypi-deploy:
    name: Build and publish Python 🐍 distributions 📦 to live PyPI
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repository
      uses: actions/checkout@master

    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        cache-dependency-glob: "uv.lock"
        enable-cache: true

    - name: Build
      run: uv build

    - name: Publish distribution 📦 to PyPI
      run: uv publish
      env:
        UV_PUBLISH_URL: https://upload.pypi.org/legacy/
        UV_PUBLISH_CHECK_URL: https://pypi.org/simple/
        UV_PUBLISH_TOKEN: ${{ secrets.TEST_PYPI_PASSWORD }}
